# Official per-line descriptions for HS chapter 22 alcohol tariff lines
# Source: https://www.canada.ca/en/department-finance/programs/international-trade-finance-policy/canadas-response-us-tariffs/complete-list-us-products-subject-to-counter-tariffs.html
# Fetched 2026-08-30. All lines effective 2025-03-04, rate 25%.

OFFICIAL_DESCRIPTIONS = {
    "2203.00.00": "Beer made from malt.",
    "2204.10.10": "Sparkling wine - Of an alcoholic strength by volume not exceeding 22.9% vol",
    "2204.10.90": "Sparkling wine - Other",
    "2204.21.10": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Wine, of an alcoholic strength by volume not exceeding 13.7% vol",
    "2204.21.21": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9%: Of an alcoholic strength by volume not exceeding 14.9% vol",
    "2204.21.22": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9%: Of an alcoholic strength by volume exceeding 14.9% vol but not exceeding 15.9% vol",
    "2204.21.23": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9%: Of an alcoholic strength by volume exceeding 15.9% vol but not exceeding 16.9% vol",
    "2204.21.24": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9%: Of an alcoholic strength by volume exceeding 16.9% vol but not exceeding 17.9% vol",
    "2204.21.25": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9%: Of an alcoholic strength by volume exceeding 17.9% vol but not exceeding 18.9% vol",
    "2204.21.26": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9%: Of an alcoholic strength by volume exceeding 18.9% vol but not exceeding 19.9% vol",
    "2204.21.27": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9%: Of an alcoholic strength by volume exceeding 19.9% vol but not exceeding 20.9% vol",
    "2204.21.28": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9%: Of an alcoholic strength by volume exceeding 20.9% vol but not exceeding 21.9% vol",
    "2204.21.31": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Wine, of an alcoholic strength by volume exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 21.9% vol but not exceeding 22.9% vol",
    "2204.21.32": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Wine, of an alcoholic strength by volume exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 22.9% vol",
    "2204.21.41": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Grape must with fermentation prevented or arrested by the addition of alcohol: Of an alcoholic strength by volume not exceeding 22.9% vol",
    "2204.21.49": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding 2 litres or less - Grape must with fermentation prevented or arrested by the addition of alcohol: Other",
    "2204.22.10": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Wine, of an alcoholic strength by volume not exceeding 13.7% vol",
    "2204.22.21": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume not exceeding 14.9% vol",
    "2204.22.22": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 14.9% vol but not exceeding 15.9% vol",
    "2204.22.23": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 15.9% vol but not exceeding 16.9% vol",
    "2204.22.24": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 16.9% vol but not exceeding 17.9% vol",
    "2204.22.25": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 17.9% vol but not exceeding 18.9% vol",
    "2204.22.26": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 18.9% vol but not exceeding 19.9% vol",
    "2204.22.27": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 19.9% vol but not exceeding 20.9% vol",
    "2204.22.28": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 20.9% vol but not exceeding 21.9% vol",
    "2204.22.31": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Wine, of an alcoholic strength by volume exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 21.9% vol but not exceeding 22.9% vol",
    "2204.22.32": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Wine, of an alcoholic strength by volume exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 22.9% vol",
    "2204.22.41": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Grape must with fermentation prevented or arrested by the addition of alcohol: Of an alcoholic strength by volume not exceeding 22.9% vol",
    "2204.22.49": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: In containers holding more than 2 litres but not more than 10 litres - Grape must with fermentation prevented or arrested by the addition of alcohol: Other",
    "2204.29.10": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Wine, of an alcoholic strength by volume not exceeding 13.7% vol",
    "2204.29.21": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume not exceeding 14.9% vol",
    "2204.29.22": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 14.9% vol but not exceeding 15.9% vol",
    "2204.29.23": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 15.9% vol but not exceeding 16.9% vol",
    "2204.29.24": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 16.9% vol but not exceeding 17.9% vol",
    "2204.29.25": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 17.9% vol but not exceeding 18.9% vol",
    "2204.29.26": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 18.9% vol but not exceeding 19.9% vol",
    "2204.29.27": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 19.9% vol but not exceeding 20.9% vol",
    "2204.29.28": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Wine, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 20.9% vol but not exceeding 21.9% vol",
    "2204.29.31": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Wine, of an alcoholic strength by volume exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 21.9% vol but not exceeding 22.9% vol",
    "2204.29.32": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Wine, of an alcoholic strength by volume exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 22.9% vol",
    "2204.29.41": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Grape must with fermentation prevented or arrested by the addition of alcohol: Of an alcoholic strength by volume not exceeding 22.9% vol",
    "2204.29.49": "Other wine; grape must with fermentation prevented or arrested by the addition of alcohol: Other - Grape must with fermentation prevented or arrested by the addition of alcohol: Other",
    "2204.30.10": "Other grape must - Of an alcoholic strength by volume not exceeding 22.9% vol",
    "2204.30.90": "Other grape must - Other",
    "2205.10.10": "In containers holding 2 litres or less - Of an alcoholic strength by volume not exceeding 18.3% vol",
    "2205.10.20": "In containers holding 2 litres or less - Of an alcoholic strength by volume exceeding 18.3% vol but not exceeding 22.9% vol",
    "2205.10.30": "In containers holding 2 litres or less - Of an alcoholic strength by volume exceeding 22.9% vol",
    "2205.90.10": "Other - Of an alcoholic strength by volume not exceeding 18.3% vol",
    "2205.90.20": "Other - Of an alcoholic strength by volume exceeding 18.3% vol but not exceeding 22.9% vol",
    "2205.90.30": "Other - Of an alcoholic strength by volume exceeding 22.9% vol",
    "2206.00.11": "Cider: Sparkling, of an alcoholic strength by volume not exceeding 22.9% vol",
    "2206.00.12": "Cider: Other sparkling",
    "2206.00.18": "Cider: Other cider, of an alcoholic strength by volume not exceeding 22.9% vol",
    "2206.00.19": "Cider: Other",
    "2206.00.21": "Prune wine: Of an alcoholic strength by volume not exceeding 22.9% vol",
    "2206.00.22": "Prune wine: Of an alcoholic strength by volume exceeding 22.9% vol",
    "2206.00.31": "Perry, sparkling: Of an alcoholic strength by volume not exceeding 22.9% vol",
    "2206.00.39": "Perry, sparkling: Other",
    "2206.00.41": "Other wine, sparkling: Of an alcoholic strength by volume not exceeding 22.9% vol",
    "2206.00.49": "Other wine, sparkling: Other",
    "2206.00.50": "Sake and other wine, not sparkling, of an alcoholic strength by volume not exceeding 13.7% vol",
    "2206.00.61": "Sake and other wine, not sparkling, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume not exceeding 14.9% vol",
    "2206.00.62": "Sake and other wine, not sparkling, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 14.9% vol but not exceeding 15.9% vol",
    "2206.00.63": "Sake and other wine, not sparkling, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 15.9% vol but not exceeding 16.9% vol",
    "2206.00.64": "Sake and other wine, not sparkling, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 16.9% vol but not exceeding 17.9% vol",
    "2206.00.65": "Sake and other wine, not sparkling, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 17.9% vol but not exceeding 18.9% vol",
    "2206.00.66": "Sake and other wine, not sparkling, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 18.9% vol but not exceeding 19.9% vol",
    "2206.00.67": "Sake and other wine, not sparkling, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 19.9% vol but not exceeding 20.9% vol",
    "2206.00.68": "Sake and other wine, not sparkling, of an alcoholic strength by volume exceeding 13.7% vol but not exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 20.9% vol but not exceeding 21.9% vol",
    "2206.00.71": "Sake and other wine, not sparkling, of an alcoholic strength by volume exceeding 21.9% vol: Of an alcoholic strength by volume not exceeding 22.9% vol",
    "2206.00.72": "Sake and other wine, not sparkling, of an alcoholic strength by volume exceeding 21.9% vol: Of an alcoholic strength by volume exceeding 22.9% vol",
    "2206.00.80": "Ginger beer and herbal beer",
    "2206.00.91": "Other: Mead",
    "2206.00.92": "Other: Other, of an alcoholic strength by volume not exceeding 22.9% vol",
    "2206.00.93": "Other: Other, of an alcoholic strength by volume exceeding 22.9% vol",
    "2208.20.00": "Spirits obtained by distilling grape wine or grape marc",
    "2208.30.00": "Whiskies",
    "2208.40.10": "Rum and other spirits obtained by distilling fermented sugar-cane products - Rum",
    "2208.40.90": "Rum and other spirits obtained by distilling fermented sugar-cane products - Other",
    "2208.50.00": "Gin and Geneva",
    "2208.60.00": "Vodka",
    "2208.70.00": "Liqueurs and cordials",
    "2208.90.10": "Other - Tequila",
    "2208.90.21": "Other - Undenatured ethyl alcohol: For use as a spirituous or alcoholic beverage or for use in the manufacture of spirituous or alcoholic beverages",
    "2208.90.29": "Other - Undenatured ethyl alcohol: Other",
    "2208.90.30": "Other - Angostura bitters",
    "2208.90.41": "Other - Spirituous fruit juices of an alcoholic strength by volume not exceeding 14.3% vol: Packaged, of an alcoholic strength by volume not exceeding 7% vol",
    "2208.90.49": "Other - Spirituous fruit juices of an alcoholic strength by volume not exceeding 14.3% vol: Other",
    "2208.90.92": "Other - Other: Fruit brandies",
    "2208.90.98": "Other - Other: Other, packaged, of an alcoholic strength by volume not exceeding 7%",
    "2208.90.99": "Other - Other: Other",
}
